### PR TITLE
Solution of Issue#78

### PR DESCRIPTION
**Pull request by janhavipunse**
Write a program to calculate the execution time of normal methods and recursive methods in Java. Prerequisite knowledge:
• Java methods
• Java recursion

### CODE REVIEW

**Comment by Chaitralikore** [comment]
Check the code and do the necessary changes.

**Comment by janhavipunse** [comment]
Which changes I have do?

**Comment by janhavipunse** [comment]
Which changes I have to do?

**Comment by janhavipunse** [comment]
What changes I have to do?

**Comment by janhavipunse** [comment]
> Check the code and do the necessary changes.

What changes I have to do?

**Comment by Chaitralikore** [comment]
@janhavipunse we can't tell that you have to fix the errors by yourself. Your deadline is extended till 30Mrach'23 11:59pm.

**Review by Vaishnavi-gaikawad — APPROVED** [review]

**Comment by janhavipunse** [comment]
As changes are approved, can you please merged it, I need to complete my next issue

**Pull request merged**
