### PR TITLE
Permutations of a String

### PR DESCRIPTION
**Pull request by PiyushaGhodake**
#28 Permutations of a String

### CODE REVIEW

**Review by Krush2311 — CHANGES_REQUESTED** [review]
Mention issue number in the comment and not in title of pr

**Comment by PiyushaGhodake** [comment]
yes done.

**Comment by PiyushaGhodake** [comment]
> Mention issue number in the comment and not in title of pr

Yes done.

**Comment by PiyushaGhodake** [comment]
@Krush2311 I have done with the changes can u check it?

**Pull request closed without merging**
