### PR TITLE
TheSkylineProblem_solution.java

### PR DESCRIPTION
**Pull request by ruchagosavi**
#36 The Skyline Problem solved

### CODE REVIEW

**Review by Krush2311 — CHANGES_REQUESTED** [review]
Please create user friendly solution, take the input from users, the dimensions of the building

**Comment by ruchagosavi** [comment]
Okk

**Comment by ruchagosavi** [comment]
Changes done!!

**Comment by ruchagosavi** [comment]
@Krush2311 changes done!!

**Review by Krush2311 — APPROVED** [review]

**Pull request merged**
