### PR TITLE
Spam detection( issue no. 20 ) solution added

### PR DESCRIPTION
**Pull request by Rasika-Kanitkar**

### CODE REVIEW

**Review by shruti-2412 — APPROVED** [review]

**Comment by shruti-2412** [comment]
@Rasika-Kanitkar is this your 2nd PR that is merged?

**Comment by Rasika-Kanitkar** [comment]
@shruti-2412 yes

**Comment by Rasika-Kanitkar** [comment]
@shruti-2412  Tu hai kya!Tu mozilla me hai ye muze aaj pata chala

**Comment by shruti-2412** [comment]
Ha mai hi hu...

**Pull request merged**
